/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiViews;

import controllers.GameController;
import daos.GameDao;
import models.*;

/**
 *
 * @author windows
 */
public class GameScreen extends javax.swing.JFrame {

    static int userId;
    static int gameId;
    GameController gameController;
    static GameDao gameDao;
    static Game game;
    boolean gameStarted;
   
    
    
    /**
     * Creates new form GameScreen
     */
    public GameScreen(int userId, int gameId, Game game) {
        this.userId = userId;
        this.gameId = gameId;        
        this.game = game;   
        this.gameDao = new GameDao(game.getUserId(),game.getGameId());
        initComponents();
        game.gameStarted();
        
    }
    
    public void AddListener(GameController gameController){
        this.gameController = gameController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos02Btn = new javax.swing.JButton();
        pos12Btn = new javax.swing.JButton();
        pos22Btn = new javax.swing.JButton();
        pos01Btn = new javax.swing.JButton();
        pos11Btn = new javax.swing.JButton();
        pos21Btn = new javax.swing.JButton();
        pos00Btn = new javax.swing.JButton();
        pos10Btn = new javax.swing.JButton();
        pos20Btn = new javax.swing.JButton();
        pos02Lbl = new javax.swing.JLabel();
        pos12Lbl = new javax.swing.JLabel();
        pos22Lbl = new javax.swing.JLabel();
        pos01Lbl = new javax.swing.JLabel();
        pos11Lbl = new javax.swing.JLabel();
        pos21Lbl = new javax.swing.JLabel();
        pos00Lbl = new javax.swing.JLabel();
        pos10Lbl = new javax.swing.JLabel();
        pos20Lbl = new javax.swing.JLabel();
        warnLbl = new javax.swing.JLabel();
        turnLbl = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        announceLbl = new javax.swing.JLabel();
        getStateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pos02Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos02BtnActionPerformed(evt);
            }
        });

        pos12Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos12BtnActionPerformed(evt);
            }
        });

        pos22Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos22BtnActionPerformed(evt);
            }
        });

        pos01Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos01BtnActionPerformed(evt);
            }
        });

        pos11Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos11BtnActionPerformed(evt);
            }
        });

        pos21Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos21BtnActionPerformed(evt);
            }
        });

        pos00Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos00BtnActionPerformed(evt);
            }
        });

        pos10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos10BtnActionPerformed(evt);
            }
        });

        pos20Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos20BtnActionPerformed(evt);
            }
        });

        pos02Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos02Lbl.setText("_____");

        pos12Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos12Lbl.setText("_____");

        pos22Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos22Lbl.setText("_____");

        pos01Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos01Lbl.setText("_____");

        pos11Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos11Lbl.setText("_____");

        pos21Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos21Lbl.setText("_____");

        pos00Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos00Lbl.setText("_____");

        pos10Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos10Lbl.setText("_____");

        pos20Lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pos20Lbl.setText("_____");

        warnLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warnLbl.setText("                      .");

        turnLbl.setText(".");

        updateBtn.setText("Update Board");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        announceLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        announceLbl.setText(".");

        getStateBtn.setText("get state");
        getStateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(pos12Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos22Lbl)
                                .addGap(81, 81, 81)
                                .addComponent(announceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pos00Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos20Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pos01Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos11Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos21Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pos02Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos12Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pos22Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(updateBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(getStateBtn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(turnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(warnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pos02Lbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos01Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos11Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos21Lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos00Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos10Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos20Lbl)))
                        .addGap(327, 327, 327)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos02Lbl)
                    .addComponent(pos22Lbl)
                    .addComponent(pos12Lbl)
                    .addComponent(announceLbl))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos01Lbl)
                    .addComponent(pos11Lbl)
                    .addComponent(pos21Lbl))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos00Lbl)
                    .addComponent(pos10Lbl)
                    .addComponent(pos20Lbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pos12Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pos02Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pos22Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(turnLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(getStateBtn)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pos01Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pos11Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pos10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pos00Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pos20Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pos21Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos02BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos02BtnActionPerformed
        // TODO add your handling code here:
       
        gameController.buttonPressed("02");     
    }//GEN-LAST:event_pos02BtnActionPerformed

    private void pos12BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos12BtnActionPerformed
        // TODO add your handling code here:
        //System.out.println("TURN IS..................... "+gameObserver.getTurn());
     
         gameController.buttonPressed("12"); 
    }//GEN-LAST:event_pos12BtnActionPerformed

    private void pos22BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos22BtnActionPerformed
       
        gameController.buttonPressed("22"); 
    }//GEN-LAST:event_pos22BtnActionPerformed

    private void pos01BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos01BtnActionPerformed
        
        gameController.buttonPressed("01"); 
    }//GEN-LAST:event_pos01BtnActionPerformed

    private void pos11BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos11BtnActionPerformed
      
        gameController.buttonPressed("11"); 
    }//GEN-LAST:event_pos11BtnActionPerformed

    private void pos21BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos21BtnActionPerformed
        
        gameController.buttonPressed("21"); 
    }//GEN-LAST:event_pos21BtnActionPerformed

    private void pos00BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos00BtnActionPerformed
        
        gameController.buttonPressed("00"); 
    }//GEN-LAST:event_pos00BtnActionPerformed

    private void pos10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos10BtnActionPerformed
       
        gameController.buttonPressed("10"); 
    }//GEN-LAST:event_pos10BtnActionPerformed

    private void pos20BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos20BtnActionPerformed
       
        gameController.buttonPressed("20"); 
    }//GEN-LAST:event_pos20BtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        //game.pollDb();
        
       // gameController.setBoardView();
        gameController.updateBoardView();
        game.checkWin();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void getStateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStateBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(gameDao.getBoard());
    }//GEN-LAST:event_getStateBtnActionPerformed

    public void setBoardLabels(int x, int y, String symbol){
        if(x==0&&y==0){
            pos00Lbl.setText(symbol);
        }else if(x==1&&y==0){
            pos10Lbl.setText(symbol);      
        }else if(x==2&&y==0){
            pos20Lbl.setText(symbol);        
        }else if(x==0&&y==1){
            pos01Lbl.setText(symbol);
        }else if(x==1&&y==1){
            pos11Lbl.setText(symbol);      
        }else if(x==2&&y==1){
            pos21Lbl.setText(symbol);        
        }else if(x==0&&y==2){
            pos02Lbl.setText(symbol);       
        }else if(x==1&&y==2){
            pos12Lbl.setText(symbol);       
        }else if(x==2&&y==2){
            pos22Lbl.setText(symbol);
        }
    }
    
    public void setWarnLabel(String warning){
        warnLbl.setText(warning);
    }
    public void setAnnounceLabel(String announcement){
        announceLbl.setText(announcement);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                new GameScreen(userId, gameId, game).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel announceLbl;
    private javax.swing.JButton getStateBtn;
    private javax.swing.JButton pos00Btn;
    private javax.swing.JLabel pos00Lbl;
    private javax.swing.JButton pos01Btn;
    private javax.swing.JLabel pos01Lbl;
    private javax.swing.JButton pos02Btn;
    private javax.swing.JLabel pos02Lbl;
    private javax.swing.JButton pos10Btn;
    private javax.swing.JLabel pos10Lbl;
    private javax.swing.JButton pos11Btn;
    private javax.swing.JLabel pos11Lbl;
    private javax.swing.JButton pos12Btn;
    private javax.swing.JLabel pos12Lbl;
    private javax.swing.JButton pos20Btn;
    private javax.swing.JLabel pos20Lbl;
    private javax.swing.JButton pos21Btn;
    private javax.swing.JLabel pos21Lbl;
    private javax.swing.JButton pos22Btn;
    private javax.swing.JLabel pos22Lbl;
    private javax.swing.JLabel turnLbl;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel warnLbl;
    // End of variables declaration//GEN-END:variables
}
