/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiViews;

import daos.GameDao;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author windows
 */
public class ScoreScreen extends javax.swing.JFrame {

    GameDao gameDao = new GameDao();
    static int userId;
    static String username;
    int wins=0;
    int losses=0;
    int draws=0;
    /**
     * Creates new form ScoreScreen
     */
    public ScoreScreen(int userId, String username) {
        this.userId = userId;
        this.username = username;
        gameDao = new GameDao();
        initComponents();
        displayScores();
    }
    
    
    
    
     public void displayScores(){
   
        String games = gameDao.getLeagueTable();
        //System.out.println(games);
        String [] gamesArr = games.split("\\s*\n\\s*");
        String [] gameDetails;
        
        for(int i=0; i<gamesArr.length; i++){
            Vector row = new Vector();
            
            gameDetails = gamesArr[i].split("\\s*,\\s*");
            
            if(gameDetails[1].equals(username)){
                switch (gameDetails[3]) {
                    case "1":
                        wins++;
                        break;
                    case "2":
                        losses++;
                        break;
                    case "3":
                        draws++;
                        break;
                    default:
                        break;
                }
                
            }else if(gameDetails[2].equals(username)){
                switch (gameDetails[3]) {
                    case "1":
                        losses++;
                        break;
                    case "2":
                        wins++;
                        break;
                    case "3":
                        draws++;
                        break;
                    default:
                        break;
                }
            } 
            
            playerNameLbl.setText(username);
            winsValLbl.setText(""+wins);
            lossesValLbl.setText(""+losses);
            drawsValLbl.setText(""+draws);
           
             
             
        }
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toMenuBtn = new javax.swing.JButton();
        winsLbl = new javax.swing.JLabel();
        lossesLbl = new javax.swing.JLabel();
        drawsLbl = new javax.swing.JLabel();
        winsValLbl = new javax.swing.JLabel();
        lossesValLbl = new javax.swing.JLabel();
        drawsValLbl = new javax.swing.JLabel();
        playerNameLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toMenuBtn.setText("Menu");
        toMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMenuBtnActionPerformed(evt);
            }
        });

        winsLbl.setText("Wins:");

        lossesLbl.setText("Losses:");

        drawsLbl.setText("Draws:");

        winsValLbl.setText(".");

        lossesValLbl.setText(".");

        drawsValLbl.setText(".");

        playerNameLbl.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winsLbl)
                            .addComponent(lossesLbl)
                            .addComponent(drawsLbl))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drawsValLbl)
                            .addComponent(lossesValLbl)
                            .addComponent(winsValLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toMenuBtn)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winsLbl)
                    .addComponent(winsValLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lossesLbl)
                    .addComponent(lossesValLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawsLbl)
                    .addComponent(drawsValLbl))
                .addGap(38, 38, 38)
                .addComponent(toMenuBtn)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMenuBtnActionPerformed
        // TODO add your handling code here:
        MenuScreen menu = new MenuScreen(userId, username);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreScreen(userId, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drawsLbl;
    private javax.swing.JLabel drawsValLbl;
    private javax.swing.JLabel lossesLbl;
    private javax.swing.JLabel lossesValLbl;
    private javax.swing.JLabel playerNameLbl;
    private javax.swing.JButton toMenuBtn;
    private javax.swing.JLabel winsLbl;
    private javax.swing.JLabel winsValLbl;
    // End of variables declaration//GEN-END:variables
}
